#pr002.yml
---

#firewall
rhbase_firewall_allow_services:
  - dns

# bind vars
bind_allow_query: 
  - any
bind_listen_ipv4:
  - any
bind_zone_master_server_ip: 172.16.192.1
bind_zone_name_servers:
  - pr001
  - pr002
  
bind_forwarders:
      - '193.190.173.1'
      - '193.190.173.2'

bind_zone_domains:
  - name: avalon.lan
    also_notify: 
      - '172.16.192.2'
    networks: 
      - '172.16'
      - '192.0.2'
    name_servers:
      - pr001
      - pr002

    hosts:
    - name: router
      ip: 
        - 192.0.2.254
        - 172.16.255.254
      aliases: 
        - gw

    - name: pu001
      ip: 192.0.2.10
      aliases:
        - www

    # - name: '@'
    #   ip: 192.0.2.10

    - name: pu002
      ip: 192.0.2.20
      aliases:
        - mail

    - name: pr001
      ip: 172.16.192.1
      aliases:
        - ns1

    - name: pr002
      ip: 172.16.192.2
      aliases:
        - ns2

    - name: pr003
      ip: 172.16.192.3
      aliases:
        - dhcp

    - name: pr004
      ip: 172.16.192.4
      aliases:
        - directory

    - name: pr010
      ip: 172.16.192.10
      aliases:
        - inside

    - name: pr011
      ip: 172.16.192.11
      aliases:
        - files
    
    mail_servers:
      - name: pu002
        preference: 10