#pr003 vars
---
rhbase_firewall_allow_services:
  - dhcp

#DHCP config
dhcp_global_domain_name_servers:
  - 172.16.255.254

#this will apply only to the known hosts, all other ranges override this
dhcp_global_default_lease_time: 43200 #12u

dhcp_global_domain_name: avalon.lan

dhcp_subnets:
  #Guests
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.0.2
    range_end: 172.16.127.254
    routers: 172.16.255.254
    default_lease_time: 14400 #4u

   #Workstations
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.128.1
    range_end: 172.16.191.254
    routers: 172.16.255.254
    default_lease_time: 14400 #4u

  #Servers, gateway
  # - ip: 172.16.0.0
  #   netmask: 255.255.0.0
  #   range_begin: 172.16.192.1
  #   range_end: 172.16.255.254
  #   routers: 172.16.255.254
  #   default_lease_time: 14400 #4u

# dhcp_hosts:
#   - name: pu001
#     mac: '08:00:27:66:5D:04'
#     ip: 192.0.2.10

#   - name: pr001
#     mac: '08:00:27:66:5D:01'
#     ip: 172.16.192.1

#   - name: pr002
#     mac: '08:00:27:66:5D:02'
#     ip: 172.16.192.2
      
#   - name: pr011
#     mac: '08:00:27:66:5D:03'
#     ip: 172.16.192.11