---
#rh-base vars
rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public

rhbase_users:
  - name: piet
    comment: 'Admin Piet'
    password: $6$Hy0j70SCpGr82jON$vQO74Zkfr.aGRkFI.k/ibw64ZQEr9hOTsIvzWJmv2PPd863eTRqPT7MRJ8ewptbeUZh2tzB38IzVcUmGGLyj.0
  #   #admin123
    groups: 
      - public
      - it
      - wheel

  - name: stevenh
    comment: 'Steven H'
    shell: /sbin/nologin
    password: $6$uyYyGPiJZrZhgG4p$Q64.qo0HLZ.9G1cS4FmLby1uVXmKONdYvsQxHhWavC9NnYyirqr/myBrSkNVA0G5lJ.FRgBFKEAhEJPZ2/M/S1
    groups:
      - public
      - management

  - name: stevenv
    comment: 'Steven VD'
    shell: /sbin/nologin
    password: $6$NFA./x5vrrg0Dyo9$QOhjkkQNZEqCI5Nln03HZ9/P26l.8te/gr771nwrgFx7Qp2ZyyItnkBJUt1ftyjSDZU9Q4zJ6uHbReDP/YQqx/
    groups:
      - public
      - technical

  - name: leend
    comment: 'Leen'
    password: $6$HX6gbQMBTopm2Lot$.DTUrWfYXBmTK2UYiYvzl6bPG0CIsHrQ7nJFQm24wYzxUqgoe7eH3rwDbmstQ6x1wpYz5Ow/JDNs2WcM/zm.O/
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: svena
    password: $6$FefnT9CUyTuBFCe1$S3jvOCJDBWjQUH5moyTsuDOIzZcHK3Pkuo/h/ybUTAuXdPwoLrmTvi/ofkaDaNfA1MwX65H2xhwslxfnstwq50
    shell: /sbin/nologin
    groups:
      - public
      - sales

  - name: nehirb
    password: $6$Z8ohxOdUlpo1tF5B$zzn7Zhwi4Xf2G.Sqo5oF6AQKx9436amqG7iooU71ZNGTJdDsvkOovBI4x7fsKdC8Czw2g1G.LCslrFX93s63P1
    groups:
      - public
      - it

  - name: alexanderd
    shell: /sbin/nologin
    password: $6$QKr1kabgsg9.4rtE$I5C1pd02mG7DhrgFP9.U5Ovw1PrfBoHZ/OdwSMeXvQ0UPRxN2AP3yHL2hRouhYzMDA2.rNSltQssf88q8GtBr1
    groups:
      - public
      - technical

  - name: krisv
    shell: /sbin/nologin
    password: $6$TKXZ0aBUE30jpEXH$cTjZ0LWupBAHGexCwag390Ad.LQsOOKpsdiylS2E0/CJ2Vwvm3Mbn2Uu/ut/F4acAzdr9aZlSGYIJDmoorcV3.
    groups:
      - public
      - management

  - name: benoitp
    shell: /sbin/nologin
    password: $6$eJg76fP0UqoblZ0N$WexFT3N7.OIem8Gjdn7fGD17Tbg2VxW6EHe0Q4LxPphItWmhcAD.arh1CiurS0GyFqztodN.2Wqe0p3eo4Lkr0
    groups:
      - sales
      - public

  - name: anc
    shell: /sbin/nologin
    password: $6$vPpUrcTZ.eODRziY$hUCDHpAdFv003gtvgEyJcT9W4mnAylIpp4qxBCZJCL1aJ0QnP0AtsT9b6THosuvuxUwotzbBoG7BPfHDWPt2J1
    groups:
      - public
      - technical

  - name: elenaa
    shell: /sbin/nologin
    password: $6$V/0yy3KdtSIjCSDJ$3.MtN62axn5jdoFsabIJdjv21VnZjcl5UZIGZFmSAPTQhG/1mInfv0VZp0ByKrR4C4kIyyrvlh17GbjLfqZxb1
    groups:
      - public
      - management

  - name: evyt
    shell: /sbin/nologin
    password: $6$Luo7y7dlRwU059qP$EsAIQr7CRT96zPTHD5BqfBNeRRcTx7NxBhyeafm3mMfsYMeTAyvtmhQyzc8haKupbVDJH1ll2myCx1FeNKtw0.
    groups:
      - public
      - technical

  - name: christophev
    password: $6$Bj6mvC.Wxjd3mA1u$QlY.e4njU0k2MFSzeHw.tqq.2GE/YeUuzdUHrfw9xv5Ci5XaeuVBWhBdGS6zpt0NMbaxnmrRLeOI1wJ3.Hgnx0
    groups:
      - public
      - it

  - name: stefaanv
    password: $6$FZz8VOsZD/y4sqca$F.L5zfMjiA4AzmJ555S7VJqzCAK1M1eiTfU/k.sUsr5Fdhm91bBqvRoIy3iAQYzObLkKwToqw3mSCrGtzJjJd0
    shell: /sbin/nologin
    groups:
      - public
      - technical

#samba vars
samba_netbios_name: FILES
samba_workgroup: AVALON
samba_map_to_guest: bad user
samba_shares:
  - name: management
    group: management
    browsable: 'no'
    valid_users: +management
    write_list: +management

  - name: technical
    group: technical
    browsable: 'yes'
    valid_users: +public
    write_list: +technical

  - name: sales
    group: sales
    browsable: 'yes'
    valid_users: +sales, +management
    write_list: +sales

  - name: it
    group: it
    browsable: 'yes'
    valid_users: +it, +management
    write_list: +it

  - name: public
    group: public
    public: 'yes'
    browsable: 'yes'
    setype: public_content_t
    write_list: +public

samba_users:
  - name: stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: leend
    password: leend
  - name: svena
    password: svena
  - name: nehirb
    password: nehirb
  - name: alexanderd
    password: alexanderd
  - name: krisv
    password: krisv
  - name: benoitp
    password: benoitp
  - name: anc
    password: anc
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: christophev
    password: christophev
  - name: stefaanv
    password: stefaanv
  - name: piet
    password: admin123

#vsftp vars
rhbase_firewall_allow_services: 
  - ftp
  - samba
vsftpd_options:
  - key: delete_failed_uploads
    value: 'YES'
  - key: ftpd_banner
    value: 'Welcome to the FTP service'

#extra permissions on each share
#public share
vsftpd_extra_permissions:
  - folder: "/srv/shares/public"
    entity: "public"
    etype: "group"
    permissions: "rwx"

#management share
  - folder: "/srv/shares/management"
    entity: "sales"
    etype: "group"
    permissions: "---"

  - folder: "/srv/shares/management"
    entity: "it"
    etype: "group"
    permissions: "---"

  - folder: "/srv/shares/management"
    entity: "management"
    etype: "group"
    permissions: "rwx"

  - folder: "/srv/shares/management"
    entity: "technical"
    etype: "group"
    permissions: "---"

#sales share
  - folder: "/srv/shares/sales"
    entity: "sales"
    etype: "group"
    permissions: "rwx"

  - folder: "/srv/shares/sales"
    entity: "it"
    etype: "group"
    permissions: "---"

  - folder: "/srv/shares/sales"
    entity: "management"
    etype: "group"
    permissions: "r-x"

  - folder: "/srv/shares/sales"
    entity: "technical"
    etype: "group"
    permissions: "---"

#it share
  - folder: "/srv/shares/it"
    entity: "it"
    etype: "group"
    permissions: "rwx"

  - folder: "/srv/shares/it"
    entity: "management"
    etype: "group"
    permissions: "r-x"

  - folder: "/srv/shares/it"
    entity: "sales"
    etype: "group"
    permissions: "---"

  - folder: "/srv/shares/it"
    entity: "technical"
    etype: "group"
    permissions: "---"

vsftpd_anonymous_enable: false
vsftpd_local_enable: true
vsftpd_local_root: /srv/shares/