---
#rh-base vars
rhbase_firewall_allow_services: 
  - samba

rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public

rhbase_users:
  - name: piet
    comment: 'Admin Piet'
    groups: 
      - public
      - it

  - name: stevenh
    comment: 'Steven H'
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: stevenv
    comment: 'Steven VD'
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: leend
    comment: 'Leen'
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: svena
    shell: /sbin/nologin
    groups:
      - public
      - sales

  - name: nehirb
    groups:
      - public
      - it

  - name: alexanderd
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: krisv
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: benoitp
    shell: /sbin/nologin
    groups:
      - sales
      - public

  - name: anc
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: elenaa
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: evyt
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: christophev
    groups:
      - public
      - it

  - name: stefaanv
    shell: /sbin/nologin
    groups:
      - public
      - technical

#samba vars
samba_netbios_name: FILES
samba_workgroup: AVALON
samba_shares:
  - name: management
    group: management
    browsable: 'no'
    valid_users: +management
    write_list: +management

  - name: technical
    group: technical
    browsable: 'yes'
    valid_users: +public
    write_list: +technical

  - name: sales
    group: sales
    browsable: 'yes'
    valid_users: +sales, +management
    write_list: +sales

  - name: it
    group: it
    browsable: 'yes'
    valid_users: +it, +management
    write_list: +it

  - name: public
    group: public
    public: 'yes'
    browsable: 'yes'
    setype: public_content_t
    write_list: +public

samba_users:
  - name: stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: leend
    password: leend
  - name: svena
    password: svena
  - name: nehirb
    password: nehirb
  - name: alexanderd
    password: alexanderd
  - name: krisv
    password: krisv
  - name: benoitp
    password: benoitp
  - name: anc
    password: anc
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: christophev
    password: christophev
  - name: stefaanv
    password: stefaanv
  - name: piet
    password: admin123