#pu001 vars
---
rhbase_firewall_allow_services:
  - http
  - https

#httpd 
httpd_ssl_certificate_key_file: 'ca.key'
httpd_ssl_certificate_file: 'ca.crt'

#mariadb vars
mariadb_databases:
  - name: wp_db
mariadb_users: 
  - name: piet
    password: testPass
    priv: 'wp_db.*:ALL'
 
mariadb_root_password: 'Ro0tP4sS'

#wordpress vars
wordpress_database: wp_db
wordpress_user: piet
wordpress_password: testPass

#fail2ban plugin
wordpress_plugins:
  - name: wp-fail2ban
    version: 4.2.7.1

#hard filter
fail2ban_filterd_path: /usr/share/wordpress/wp-content/plugins/wp-fail2ban/filters.d/
fail2ban_services:
  - name: wordpress
    port: http, https
    filter: wordpress-hard
    logpath: /var/log/auth.log
    maxretry: 3
    findtime: 120
    bantime: 300