#pu001 vars
---
rhbase_firewall_allow_services:
  - http
  - https

#mariadb vars
mariadb_databases:
  - name: wp_db
mariadb_users: 
  - name: piet
    password: testPass
    priv: 'wp_db.*:ALL'
 
mariadb_root_password: 'Ro0tP4sS'

#wordpress vars
wordpress_database: wp_db
wordpress_user: piet
wordpress_password: testPass