- name: Start and enable firewalld
  service: name=firewalld state=started enabled=yes

- name: "set motd banner"
  template:
    src: "motd.j2"
    dest: "/etc/motd"

# - name: Set authorized key taken from file
#   authorized_key:
#     user: piet
#     state: present
#     key: "{{ lookup('file', '/vagrant/ansible/files/id_rsa.pub') }}"