# group_vars/all.yml
# Variables visible to all nodes
---
motd_contact_email: 'piet.jacobs@student.hogent.be'
httpd_ssl_certificate_key_file: 'ca.key'
httpd_ssl_certificate_file: 'ca.crt'

#mariadb vars
mariadb_databases:
  - name: wordpress
mariadb_users: 
  - name: piet
    password: testPass
    priv: '*.*:ALL'
 
mariadb_root_password: 'Ro0tP4sS'

# bind vars
bind_allow_query: 
  - any
bind_listen_ipv4:
  - any
bind_zone_master_server_ip: 172.16.192.1
bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
bind_zone_domains:
  - name: 'avalon.lan'
    networks: 
      - '172.16.192'
      - '192'
    name_servers:
      - pr001
      - pr002

    hosts:
      #forward lookups
    - name: pu001
      ip: 192.0.2.10
      aliases:
        - www

    - name: pu002
      ip: 192.0.2.20
      aliases:
        - mail

    - name: pr001
      ip: 172.16.192.1
      aliases:
        - ns1

    - name: pr002
      ip: 172.16.192.2
      aliases:
        - ns2

    - name: pr003
      ip: 172.16.192.3
      aliases:
        - dhcp

    - name: pr004
      ip: 172.16.192.4
      aliases:
        - directory

    - name: pr010
      ip: 172.16.192.10
      aliases:
        - inside

    - name: pr011
      ip: 172.16.192.11
      aliases:
        - files

    #reverse lookups

    #...
    mail_servers:
      - name: pu002
        preference: 10


#rh-base vars
rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public

rhbase_users:
  - name: stevenh
    comment: 'Steven H'
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: stevenv
    comment: 'Steven VD'
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: leend
    comment: 'Leen'
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: svena
    shell: /sbin/nologin
    groups:
      - public
      - sales

  - name: nehirb
    groups:
      - public
      - it

  - name: alexanderd
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: krisv
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: benoitp
    shell: /sbin/nologin
    groups:
      - public
      - sales

  - name: anc
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: elenaa
    shell: /sbin/nologin
    groups:
      - public
      - management

  - name: evyt
    shell: /sbin/nologin
    groups:
      - public
      - technical

  - name: christophev
    groups:
      - public
      - it

  - name: stefaanv
    shell: /sbin/nologin
    groups:
      - public
      - technical

#samba vars
samba_netbios_name: FILES
samba_workgroup: AVALON
samba_shares:
  - name: management
    group: management
    browsable: 'no'
    write_list: +management

  - name: technical (software development)
    group: technical
    browsable: 'yes'
    write_list: +technical

  - name: sales
    group: sales
    browsable: 'no'
    valid_users: +management
    write_list: +sales

  - name: it (system administrator)
    group: it
    browsable: 'no'
    valid_users: +management
    write_list: +it

  - name: public
    group: public
    public: 'yes'
    browsable: 'yes'

samba_users:
  - name: stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: leend
    password: leend
  - name: svena
    password: svena
  - name: nehirb
    password: nehirb
  - name: alexanderd
    password: alexanderd
  - name: krisv
    password: krisv
  - name: benoitp
    password: benoitp
  - name: anc
    password: anc
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: christophev
    password: christophev
  - name: stefaanv
    password: stefaanv
  - name: piet
    password: admin123


