# site.yml
---

- hosts: pu001
  become: true
  remote_user: root
  roles:
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress



- hosts: all
  tasks:
    - name: start firewalld
      service: 
        name: firewalld
        state: started

    - name: Enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: allow http through firewalld
      firewalld:
          service: http
          permanent: yes
          state: enabled

    - name: allow https through firewalld
      firewalld:
          service: https
          permanent: yes
          state: enabled

    - name: restart firewalld service
      service:
        name: firewalld
        state: restarted

    - name: install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: install nano
      yum: 
        name: nano
        state: present
        update_cache: yes

    - name: install tree
      yum: 
        name: tree
        state: present
        update_cache: yes

    - name: install vim-enhanced
      yum: 
        name: vim-enhanced
        state: present
        update_cache: yes

    - name: install bind-utils
      yum: 
        name: bind-utils
        state: present
        update_cache: yes

    - name: install bash-completion
      yum: 
        name: bash-completion
        state: present
        update_cache: yes

    - name: make SELinux enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: add user 'piet' with admin rights
      user:
        name: piet
        comment: Piet Jacobs
        group: "wheel"

    - name: "set motd banner"
      template:
        src: "motd.j2"
        dest: "/etc/motd"

    - name: Set authorized key taken from file
      authorized_key:
        user: piet
        state: present
        key: "{{ lookup('file', '/vagrant/ansible/group_vars/id_rsa.pub') }}"