# site.yml
---
- hosts: all
  become: true
  remote_user: root
  roles:
    - bertvv.rh-base
    - ansible-fail2ban

- hosts: pu001
  become: true
  remote_user: root
  roles:
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress

- hosts: pr001,pr002
  become: true
  remote_user: root
  roles:
    - bertvv.bind

- hosts: pr011
  become: true 
  remote_user: root
  roles:
    - bertvv.samba
    - bertvv.vsftpd

- hosts: pr003
  become: true
  remote_user: root
  roles:
    - bertvv.dhcp

- hosts: internal
  become: true
  remote_user: root
  tasks:
    # - name: Remove default gateway
    #   shell: ip route flush 0/0
    - name: Set default gateway
      shell: route add default gw 172.16.255.254
    - name: Set dns servers
      shell: printf "nameserver 172.16.255.254" > /etc/resolv.conf


- hosts: dmz
  become: true
  remote_user: root
  tasks:
    - name: Set default gateway
      shell: route add default gw 192.0.2.254
    - name: Set dns servers
      shell: printf "nameserver 192.0.2.254" > /etc/resolv.conf

