# site.yml
---
- hosts: all
  become: true
  remote_user: root
  roles:
    - bertvv.rh-base
    - basic-config

- hosts: pu001
  become: true
  remote_user: root
  roles:
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress

- hosts: pr001
  become: true
  remote_user: root
  roles:
    - bertvv.bind

- hosts: pr011
  become: true 
  remote_user: root
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd

