# site.yml
---
- hosts: all
  become: true
  remote_user: root
  roles:
    - bertvv.rh-base
    - basic-config
    - ansible-fail2ban

- hosts: pu001
  become: true
  remote_user: root
  roles:
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress

- hosts: pr001,pr002
  become: true
  remote_user: root
  roles:
    - bertvv.bind

- hosts: pr011
  become: true 
  remote_user: root
  roles:
    - bertvv.samba
    - bertvv.vsftpd

- hosts: pr003
  become: true
  remote_user: root
  roles:
    - bertvv.dhcp
